image: node:18.10

definitions: 
  steps:
    - step: &vue-lint-test-build
        name: 'Vue: Lint, tests and build'
        caches:
          - node
        script:
          - git submodule update --init
          - cd org.knime.base.views/js-src/vue
          - npm ci
          - npm run ci:lint
          - npm run coverage -- --ci
          - npm run build
          - npm run ci:audit
        artifacts:
          - org.knime.base.views/js-src/vue/dist/**

pipelines:
  pull-requests:
    '**':
      - parallel:
        - step: *vue-lint-test-build
  branches:
    master:
      - parallel:
        - step: *vue-lint-test-build